export type Section = { type: "p" | "h2"; text: string };
export type Article = {
  slug: string;
  title: string;
  description: string;
  date: string;
  readingMinutes: number;
  body: Section[];
  faq?: { q: string; a: string }[];
  steps?: { name: string; text: string }[];
};

export const articles: Article[] = [
  {
    slug: "meritking-uyelik-nasil-acilir",
    title: "Meritking Üyelik Nasıl Açılır? Adım Adım Kayıt Rehberi",
    description:
      "Meritking üyelik açma adımları: kayıt formunda istenen bilgiler, doğrulama, sık yapılan hatalar ve hesabınızı ilk kez kullanıma hazırlama.",
    date: "2026-08-26",
    readingMinutes: 7,
    body: [
      { type: "p", text: "Meritking üyelik açmak birkaç dakikalık bir işlemdir, ancak kayıt sırasında girilen bilgilerin doğruluğu ilerideki ödeme işlemlerini doğrudan etkiler. Bu rehberde kayıt formunun her adımını, hangi bilginin neden istendiğini ve yeni kullanıcıların en sık düştüğü hataları ele alıyoruz." },
      { type: "h2", text: "Kayıt Öncesi Hazırlık" },
      { type: "p", text: "Kayda başlamadan önce kimlik belgenizdeki ad ve soyadın tam yazımını, geçerli bir e-posta adresini ve aktif kullandığınız cep telefonu numarasını hazır bulundurun. Hesap adınız ile ödeme yöntemlerinizdeki isim birebir aynı olmalıdır; bu, ilerideki para çekme işlemlerinde gecikme yaşamamanın en önemli koşuludur." },
      { type: "h2", text: "Formda İstenen Bilgiler" },
      { type: "p", text: "Standart kayıt formu ad, soyad, doğum tarihi, e-posta, telefon ve şifre alanlarından oluşur. Doğum tarihi yaş sınırı denetimi için zorunludur; 18 yaşından küçük kullanıcıların üyeliği kabul edilmez. Telefon numarası hem güvenlik doğrulaması hem de hesap kurtarma için kullanılır, bu yüzden gerçekten erişebildiğiniz bir numara girin." },
      { type: "h2", text: "Şifre Seçimi" },
      { type: "p", text: "Şifrenizi başka hiçbir sitede kullanmadığınız, en az on iki karakterlik bir kombinasyon olarak belirleyin. Büyük harf, küçük harf, rakam ve sembol karışımı tercih edin. Bir şifre yöneticisi kullanıyorsanız şifreyi oradan üretmek en pratik yoldur; ezberlemeye çalışıp basit bir kombinasyon seçmek hesabınızı gereksiz riske atar." },
      { type: "h2", text: "E-posta ve Telefon Doğrulaması" },
      { type: "p", text: "Kayıt tamamlandıktan sonra e-posta adresinize bir onay bağlantısı, telefonunuza ise kısa bir doğrulama kodu gelir. Her iki doğrulamayı da tamamlamadan bazı işlemler kısıtlı kalabilir. Onay e-postası gelmiyorsa spam veya tanıtımlar klasörünü kontrol edin; birkaç dakika içinde ulaşmazsa yeniden gönderim talep edebilirsiniz." },
      { type: "h2", text: "Sık Yapılan Kayıt Hataları" },
      { type: "p", text: "En yaygın hata, ad soyadın kimlikten farklı yazılmasıdır; kısaltma kullanmak veya Türkçe karakterleri atlamak sonradan düzeltme talebi gerektirir. İkinci sık hata, başkasına ait ödeme yöntemi tanımlamaktır. Hesap sahibi ile ödeme yöntemi sahibinin aynı kişi olması zorunludur, aksi halde çekim talepleri reddedilir." },
      { type: "h2", text: "Hesabı İlk Kullanıma Hazırlama" },
      { type: "p", text: "Üyelik açıldıktan sonra ilk yapılması gereken, hesap ayarlarından limit tercihlerinizi gözden geçirmektir. Günlük veya haftalık yatırım limiti belirlemek, bütçenizi kontrol altında tutmanın en etkili yoludur. Bildirim tercihlerinizi de bu aşamada ayarlayarak yalnızca gerçekten ilgilendiğiniz duyuruları almayı seçebilirsiniz." },
      { type: "p", text: "Özetle, doğru bilgilerle açılan ve doğrulaması tamamlanmış bir hesap, ilerideki tüm işlemleri sorunsuz kılar. 18+ · Oyun bir eğlence biçimidir, kazanç garantisi değildir; lütfen sorumlu oynayın." },
    ],
    faq: [
      { q: "Meritking üyelik ücretli mi?", a: "Hayır, hesap açmak ücretsizdir. Yalnızca oyun oynamak için hesabınıza bakiye yüklemeniz gerekir." },
      { q: "Tek kişi birden fazla hesap açabilir mi?", a: "Hayır. Kişi başına tek hesap kuralı geçerlidir; birden fazla hesap tespit edildiğinde hesaplar kapatılabilir." },
      { q: "Kayıtta yanlış bilgi girdim, düzeltebilir miyim?", a: "Ad, soyad ve doğum tarihi gibi kimlik bilgileri müşteri hizmetleri üzerinden belge ibrazıyla düzeltilir. E-posta ve telefon hesap ayarlarından güncellenebilir." },
      { q: "Doğrulama kodu telefonuma gelmiyor, ne yapmalıyım?", a: "Numaranın doğru girildiğini kontrol edin, şebeke çekim gücünüzü teyit edin ve birkaç dakika bekleyip yeniden kod isteyin. Sorun sürerse destek ekibine yazın." },
      { q: "Üyelik için kimlik belgesi şart mı?", a: "Kayıt anında zorunlu değildir, ancak para çekme aşamasında kimlik doğrulaması istenir. Belgelerinizi önceden hazır bulundurmak süreci hızlandırır." },
      { q: "Hesabımı sonradan kapatabilir miyim?", a: "Evet. Müşteri hizmetlerine talep ileterek hesabınızı kalıcı olarak kapatabilir veya belirli bir süre için dondurabilirsiniz." },
    ],
    steps: [
      { name: "Bilgileri haz\u0131rla", text: "Kimlik belgenizdeki ad ve soyad\u0131n tam yaz\u0131m\u0131n\u0131, ge\u00e7erli bir e-posta adresini ve aktif kulland\u0131\u011f\u0131n\u0131z cep telefonu numaras\u0131n\u0131 haz\u0131r bulundurun." },
      { name: "Kay\u0131t formunu doldur", text: "Ad, soyad, do\u011fum tarihi, e-posta, telefon ve \u015fifre alanlar\u0131n\u0131 doldurun. Ad soyad\u0131 kimli\u011finizdeki gibi yaz\u0131n; \u00f6deme i\u015flemlerinde bu bilgi esas al\u0131n\u0131r." },
      { name: "G\u00fc\u00e7l\u00fc \u015fifre belirle", text: "Ba\u015fka hi\u00e7bir sitede kullanmad\u0131\u011f\u0131n\u0131z, en az on iki karakterlik bir \u015fifre se\u00e7in. B\u00fcy\u00fck harf, k\u00fc\u00e7\u00fck harf, rakam ve sembol kar\u0131\u015ft\u0131r\u0131n." },
      { name: "E-posta ve telefonu do\u011frula", text: "E-posta adresinize gelen onay ba\u011flant\u0131s\u0131na t\u0131klay\u0131n ve telefonunuza gelen do\u011frulama kodunu girin. Her iki do\u011frulama da tamamlanmal\u0131d\u0131r." },
      { name: "Hesab\u0131 kullan\u0131ma haz\u0131rla", text: "Hesap ayarlar\u0131ndan g\u00fcnl\u00fck veya haftal\u0131k yat\u0131r\u0131m limiti belirleyin ve bildirim tercihlerinizi ayarlay\u0131n." },
    ],
  },
  {
    slug: "para-cekme-suresi-ve-limitleri",
    title: "Para Çekme Süresi ve Limitleri Nasıl İşler?",
    description:
      "Bahis sitelerinde para çekme süreleri, yöntem bazlı limitler, işlemi geciktiren nedenler ve çekim talebini sorunsuz sonuçlandırma yolları.",
    date: "2026-08-18",
    readingMinutes: 8,
    body: [
      { type: "p", text: "Para çekme, kullanıcıların en çok soru sorduğu konudur ve süreyi belirleyen tek bir faktör yoktur. Seçtiğiniz yöntem, hesabınızın doğrulama durumu ve talebin gönderildiği saat birlikte işleyerek toplam süreyi oluşturur. Bu yazıda süreci baştan sona açıklıyoruz." },
      { type: "h2", text: "Süreç Nasıl İşler?" },
      { type: "p", text: "Çekim talebi oluşturduğunuzda işlem önce bekleyen talepler kuyruğuna girer ve finans ekibi tarafından incelenir. Onaydan sonra tutar ödeme sağlayıcısına iletilir; buradan hesabınıza ulaşması yöntemin kendi işlem süresine bağlıdır. Yani toplam süre, site içi onay ile sağlayıcı transfer süresinin toplamıdır." },
      { type: "h2", text: "Yöntem Bazında Tipik Süreler" },
      { type: "p", text: "Elektronik cüzdanlar genellikle en hızlı seçenektir ve onay sonrası kısa sürede sonuçlanır. Banka havalesi, bankaların çalışma saatlerine bağlı olduğu için hafta sonu ve resmi tatillerde uzayabilir. Kripto transferleri ağ yoğunluğuna göre değişir; ağ sıkışıksa doğrulama beklemesi normalden uzun sürebilir." },
      { type: "h2", text: "Minimum ve Maksimum Limitler" },
      { type: "p", text: "Her yöntemin kendi alt ve üst sınırı vardır. Alt sınırın altındaki talepler işleme alınmaz, üst sınırı aşan tutarlar ise otomatik olarak birden fazla işleme bölünebilir. Yüksek tutarlı çekimlerde ek doğrulama istenmesi standart bir uygulamadır ve süreci bir miktar uzatır." },
      { type: "h2", text: "Çekimi Geciktiren En Sık Nedenler" },
      { type: "p", text: "Birinci neden tamamlanmamış kimlik doğrulamasıdır; belgeleri önceden yüklemek bu gecikmeyi tamamen ortadan kaldırır. İkinci neden, bonus çevrim şartının henüz tamamlanmamış olmasıdır. Üçüncü neden ise hesap adı ile ödeme yöntemi sahibinin uyuşmamasıdır ki bu durumda talep doğrudan reddedilir." },
      { type: "h2", text: "Talebi Sorunsuz Sonuçlandırmak İçin" },
      { type: "p", text: "Kimlik doğrulamanızı ilk yatırımdan önce tamamlayın, aktif bir bonusunuz varsa çevrim durumunu kontrol edin ve çekim yöntemi olarak yatırım yaptığınız yöntemi tercih edin. Talebi hafta içi mesai saatleri içinde göndermek, banka kaynaklı beklemeleri azaltır." },
      { type: "h2", text: "Talep Beklemede Kalırsa" },
      { type: "p", text: "Beklenen süreyi aşan bir talep için önce hesap bildirimlerinizi kontrol edin; çoğu zaman eksik belge bildirimi orada yer alır. Bildirim yoksa müşteri hizmetlerine talep numarasıyla birlikte yazın. Aynı talebi tekrar oluşturmak süreci hızlandırmaz, aksine kuyruğu karmaşıklaştırır." },
      { type: "p", text: "Kısacası doğrulaması tamam, bonusu kapanmış ve kendi adına kayıtlı yöntemle yapılan çekimler beklenen sürede sonuçlanır. 18+ · Oyun bir eğlence biçimidir, kazanç garantisi değildir; lütfen sorumlu oynayın." },
    ],
    faq: [
      { q: "Para çekme talebini iptal edebilir miyim?", a: "Talep henüz beklemede ise çoğu durumda iptal edilebilir. Onaylanıp sağlayıcıya iletildikten sonra iptal mümkün değildir." },
      { q: "Yatırdığım yöntemden farklı bir yöntemle çekebilir miyim?", a: "Genellikle hayır. Kaynak doğrulaması gereği çekim, yatırım yapılan yöntemle aynı olmalıdır. İstisnalar destek onayına bağlıdır." },
      { q: "Çekim işlemlerinden komisyon alınır mı?", a: "Site tarafında genellikle komisyon uygulanmaz, ancak ödeme sağlayıcınız veya bankanız kendi ücretini yansıtabilir." },
      { q: "Hafta sonu para çekebilir miyim?", a: "Talebi her zaman oluşturabilirsiniz. Elektronik cüzdanlar hafta sonu da işler; banka havalesi ilk iş gününe sarkabilir." },
      { q: "Neden ek belge isteniyor?", a: "Yüksek tutarlı işlemlerde ve ilk çekimde kimlik ile adres doğrulaması standart bir güvenlik adımıdır." },
      { q: "Kısmi çekim yapabilir miyim?", a: "Evet, bakiyenizin tamamını çekmek zorunda değilsiniz. Alt limitin üzerinde kalmak kaydıyla istediğiniz tutarı talep edebilirsiniz." },
    ],
  },
  {
    slug: "canli-bahis-nasil-oynanir",
    title: "Canlı Bahis Nasıl Oynanır? Yeni Başlayanlar İçin Rehber",
    description:
      "Canlı bahis nedir, maç sırasında oranlar neden değişir, hangi bahis türleri sunulur ve yeni başlayanların dikkat etmesi gereken noktalar.",
    date: "2026-08-09",
    readingMinutes: 8,
    body: [
      { type: "p", text: "Canlı bahis, karşılaşma başladıktan sonra devam eden ve oyunun akışına göre oranların sürekli güncellendiği bahis türüdür. Maç öncesi bahisten temel farkı, kararınızı sahadaki gerçek performansı görerek vermenizdir. Bu rehberde canlı bahsin nasıl işlediğini ve nelere dikkat edilmesi gerektiğini anlatıyoruz." },
      { type: "h2", text: "Oranlar Neden Sürekli Değişir?" },
      { type: "p", text: "Canlı oranlar, maçtaki her önemli olayla birlikte yeniden hesaplanır. Gol, kırmızı kart, sakatlık veya uzun süreli baskı gibi gelişmeler olasılıkları değiştirir ve oran buna göre yükselir ya da düşer. Bu nedenle canlı bahiste oran, sabit bir değer değil anlık bir fotoğraftır." },
      { type: "h2", text: "Sık Kullanılan Canlı Bahis Türleri" },
      { type: "p", text: "Maç sonucu en temel seçenektir. Bunun yanında toplam gol alt ve üst bahisleri, sıradaki golü kim atacak, korner sayısı ve kart bahisleri yaygın olarak sunulur. Bazı karşılaşmalarda oyuncu bazlı istatistik bahisleri de açılır. Hangi türü seçerseniz seçin, kuralı bahis oynamadan önce okumak yanlış anlamayı önler." },
      { type: "h2", text: "Bahis Kabul Gecikmesi" },
      { type: "p", text: "Canlı bahiste kuponunuz anında değil, kısa bir onay süresi sonunda kabul edilir. Bu süre içinde oran değişirse bahis reddedilebilir veya yeni oranla onayınıza sunulabilir. Bu bir aksaklık değil, oranların hızla değiştiği ortamda hem kullanıcıyı hem siteyi koruyan standart bir mekanizmadır." },
      { type: "h2", text: "Yayın Gecikmesine Dikkat" },
      { type: "p", text: "Televizyon veya internet yayını, sahadaki olaya göre birkaç saniye gecikmeli olabilir. Ekranda henüz görmediğiniz bir gol, sistemde çoktan işlenmiş olabilir. Bu yüzden yalnızca yayına bakarak son saniye bahsi oynamak beklediğinizden farklı sonuçlar doğurabilir." },
      { type: "h2", text: "Yeni Başlayanlar İçin Öneriler" },
      { type: "p", text: "İzlediğiniz ve kurallarını bildiğiniz bir spor dalıyla başlayın; tanımadığınız bir ligde canlı karar vermek zordur. Aynı anda çok sayıda maç takip etmek yerine tek karşılaşmaya odaklanın. Kuponu oynamadan önce neden o seçeneği tercih ettiğinizi kendinize açıklayabiliyorsanız, karar duygusal değil gözleme dayalı demektir." },
      { type: "h2", text: "Kaçınılması Gereken Alışkanlıklar" },
      { type: "p", text: "Kaybettikten hemen sonra zararı kapatmak için daha yüksek tutarla bahis yapmak, canlı bahiste en sık görülen ve en maliyetli hatadır. Aynı şekilde, sırf maç oynanıyor diye sürekli kupon açmak da bütçeyi hızla eritir. Bahis yapmadığınız bir maçı izlemek de tamamen geçerli bir seçenektir." },
      { type: "p", text: "Canlı bahis, gözleme dayalı ve tempolu bir deneyimdir; disiplinle oynandığında keyiflidir. 18+ · Oyun bir eğlence biçimidir, kazanç garantisi değildir; lütfen sorumlu oynayın." },
    ],
    faq: [
      { q: "Canlı bahis ile maç öncesi bahis arasındaki fark nedir?", a: "Maç öncesi bahis karşılaşma başlamadan oynanır ve oran sabittir. Canlı bahis maç sürerken oynanır, oranlar oyunun akışına göre sürekli güncellenir." },
      { q: "Canlı bahis kuponum neden reddedildi?", a: "Onay süresi içinde oran değiştiği için olabilir. Bu durumda bahis ya reddedilir ya da yeni oranla tekrar onayınıza sunulur." },
      { q: "Canlı bahiste kupon bozdurma var mı?", a: "Birçok karşılaşmada erken kazanç seçeneği sunulur. Teklif edilen tutar, o andaki olasılıklara göre hesaplanır ve potansiyel kazançtan düşüktür." },
      { q: "Hangi sporlarda canlı bahis oynanabilir?", a: "Futbol, basketbol, tenis ve voleybol başta olmak üzere çok sayıda branşta canlı bahis sunulur. Seçenek çeşitliliği maçın önemine göre değişir." },
      { q: "Canlı bahiste kombine kupon yapılabilir mi?", a: "Evet, devam eden birden fazla karşılaşmayı aynı kuponda birleştirebilirsiniz. Ancak her seçim ayrı onay süresine tabidir." },
      { q: "Maç iptal olursa canlı bahsim ne olur?", a: "İptal veya ertelenen karşılaşmalarda ilgili seçim genellikle geçersiz sayılır ve kupondan düşülerek bahis tutarı iade edilir." },
    ],
  },
  {
    slug: "bahiste-bankroll-yonetimi",
    title: "Bahiste Bankroll Yönetimi: Bütçenizi Nasıl Korursunuz?",
    description:
      "Bankroll nedir, birim bahis mantığı nasıl kurulur, kayıp kovalamaktan nasıl kaçınılır ve uzun vadede bütçeyi koruyan pratik kurallar.",
    date: "2026-07-31",
    readingMinutes: 7,
    body: [
      { type: "p", text: "Bankroll, bahis için ayırdığınız ve kaybetmeyi göze aldığınız toplam bütçedir. Bu tutarın günlük harcamalarınızdan tamamen ayrı durması, sorumlu oyunun temel şartıdır. Bankroll yönetimi ise bu bütçeyi nasıl böleceğinizi ve her kupona ne kadar ayıracağınızı belirleyen basit bir disiplindir." },
      { type: "h2", text: "Birim Bahis Mantığı" },
      { type: "p", text: "En yaygın yaklaşım, bütçeyi eşit birimlere bölmek ve her kupona bir birim yatırmaktır. Örneğin bütçenizi yüz birime bölerseniz, tek bir kupona bütçenizin yüzde biri kadar yatırmış olursunuz. Bu yöntem, arka arkaya gelen kayıpların bütçeyi bitirmesini engeller ve kararlarınızı sakin tutar." },
      { type: "h2", text: "Neden Sabit Tutar?" },
      { type: "p", text: "Kendinize güvendiğiniz maçta tutarı katlamak cazip görünür, ancak bu yaklaşım tek bir yanlış tahminin uzun süreli birikimi silmesine yol açar. Sabit birim, hem iyi hem kötü serilerde aynı davranmanızı sağlar. İstisna yapmak istiyorsanız bunu önceden yazılı bir kurala bağlayın, anlık hisle değil." },
      { type: "h2", text: "Kayıp Kovalama Tuzağı" },
      { type: "p", text: "Kayıp kovalama, kaybedilen tutarı geri almak için giderek daha büyük bahisler yapmaktır ve bütçe eritmenin en hızlı yoludur. Matematiksel olarak da işlemez; her yeni bahis önceki sonuçtan bağımsızdır. Bir seans içinde belirlediğiniz kayıp sınırına ulaştıysanız, o gün için durmak en doğru karardır." },
      { type: "h2", text: "Kayıt Tutmanın Değeri" },
      { type: "p", text: "Oynadığınız kuponları, tutarları ve sonuçları basit bir tabloya yazmak, alışkanlıklarınızı görünür kılar. Çoğu kişi hangi bahis türünde ne kadar harcadığını tahmin ederken yanılır. Birkaç haftalık kayıt, hangi alanda gereksiz risk aldığınızı net biçimde gösterir." },
      { type: "h2", text: "Seans Limitleri Belirlemek" },
      { type: "p", text: "Oturmadan önce iki sayı belirleyin: o seansta harcayacağınız en yüksek tutar ve oynayacağınız en uzun süre. Her ikisi de aşıldığında oturum biter. Bu kural basit görünse de, kararı duygusal anda değil sakin anda vermenizi sağladığı için etkilidir." },
      { type: "h2", text: "Bonusları Bütçeye Dahil Etmeyin" },
      { type: "p", text: "Bonus tutarını kendi paranızmış gibi hesaba katmak, gerçek bakiyenizi olduğundan büyük göstermenize yol açar. Bonusları çevrim şartı tamamlanana kadar ayrı düşünmek, bütçe tablonuzu gerçekçi tutar." },
      { type: "p", text: "İyi bir bütçe disiplini kazancı garanti etmez, ancak oyunu sürdürülebilir ve keyifli kılar. 18+ · Oyun bir eğlence biçimidir, kazanç garantisi değildir; lütfen sorumlu oynayın." },
    ],
    faq: [
      { q: "Bankroll ne kadar olmalı?", a: "Kaybetmeniz halinde günlük yaşamınızı etkilemeyecek bir tutar olmalıdır. Sabit bir rakam yoktur; ölçü, o parayı kaybetmenin sizi zora sokmamasıdır." },
      { q: "Birim bahis yüzdesi kaç olmalı?", a: "Yaygın yaklaşım bütçenin yüzde biri ile yüzde ikisi arasıdır. Daha yüksek yüzdeler kısa serilerde bütçeyi hızla tüketebilir." },
      { q: "Kazandıkça bahis tutarını artırmalı mıyım?", a: "Bütçe büyüdükçe birim tutarı orantılı güncellemek makuldür. Ancak bunu tek tek kuponlarda değil, belirli aralıklarla yapın." },
      { q: "Kayıp kovalamayı nasıl engellerim?", a: "Seans başına kayıp sınırı belirleyin ve sınıra ulaşınca oturumu kapatın. Sınırı anlık olarak yükseltmemek en kritik kuraldır." },
      { q: "Kayıt tutmak gerçekten fark yaratır mı?", a: "Evet. Harcama ve sonuçları yazmak, tahmine dayalı algıyı gerçek verilerle değiştirir ve gereksiz risk aldığınız alanları görünür kılar." },
      { q: "Oyun kontrolden çıkıyorsa ne yapmalıyım?", a: "Hesap ayarlarından limit koyun veya hesabınızı geçici olarak dondurun. Ayrıca bağımsız destek hatlarından profesyonel yardım alabilirsiniz." },
    ],
  },
  {
    slug: "kombine-ve-sistem-bahis-farki",
    title: "Kombine ve Sistem Bahis Arasındaki Fark Nedir?",
    description:
      "Kombine kupon ile sistem bahsin farkı, oranların nasıl çarpıldığı, sistem bahsin riski nasıl dağıttığı ve hangi durumda hangisinin uygun olduğu.",
    date: "2026-07-22",
    readingMinutes: 7,
    body: [
      { type: "p", text: "Kombine ve sistem, birden fazla seçimi tek kuponda birleştirmenin iki farklı yoludur. Aralarındaki fark, kuponun kazanması için kaç seçimin tutması gerektiğidir. Bu ayrımı anlamak, aynı seçimlerle çok farklı risk profilleri kurmanızı sağlar." },
      { type: "h2", text: "Kombine Kupon Nasıl İşler?" },
      { type: "p", text: "Kombine kuponda tüm seçimlerin tutması gerekir. Seçimlerin oranları birbiriyle çarpılır ve toplam oran ortaya çıkar. Bu yapı yüksek getiri sunar, ancak tek bir yanlış tahmin kuponun tamamını götürür. Seçim sayısı arttıkça potansiyel kazanç büyür, kazanma olasılığı ise hızla düşer." },
      { type: "h2", text: "Sistem Bahis Nasıl İşler?" },
      { type: "p", text: "Sistem bahiste seçimleriniz alt kombinasyonlara bölünür ve her kombinasyon ayrı bir kupon gibi değerlendirilir. Örneğin dört seçimle kurulan üçlü sistemde, bu dört seçimin üçerli tüm kombinasyonları oynanmış olur. Seçimlerden biri tutmasa bile diğer kombinasyonlar kazanabildiği için kupon tamamen boşa gitmez." },
      { type: "h2", text: "Maliyet Farkı" },
      { type: "p", text: "Sistem bahis, birden fazla kupon oynamak anlamına geldiği için aynı birim tutarda kombineye göre daha pahalıdır. Dörtlü seçimde üçlü sistem dört ayrı kombinasyon üretir; birim tutarınız bu sayıyla çarpılır. Bu yüzden sistem kurarken toplam maliyeti oynamadan önce mutlaka kontrol edin." },
      { type: "h2", text: "Hangi Durumda Hangisi?" },
      { type: "p", text: "Seçimlerinizin hepsine yüksek güven duyuyorsanız ve bütçeniz sınırlıysa kombine daha verimlidir. Buna karşılık seçimlerden bir ikisinin sürprize açık olduğunu düşünüyorsanız, sistem bahis riski dağıtarak kuponu tamamen kaybetme ihtimalini azaltır." },
      { type: "h2", text: "Sık Yapılan Hata" },
      { type: "p", text: "En yaygın hata, kombineye yalnızca oranı yükseltmek için düşük güvenli seçim eklemektir. Eklenen her zayıf seçim, kuponun tamamının kazanma olasılığını çarpan etkisiyle düşürür. Oranı büyütmek kazancı garanti etmez, yalnızca beklenen olasılığı küçültür." },
      { type: "h2", text: "Küçük Kuponların Avantajı" },
      { type: "p", text: "İki ya da üç seçimlik kuponlar, on seçimlik kuponlara göre çok daha yüksek sonuçlanma şansı taşır. Uzun vadede oyunu sürdürülebilir kılan da budur. Büyük kombineler eğlenceli olabilir, ancak bütçenin ana kısmını bunlara ayırmak makul değildir." },
      { type: "p", text: "Kombine ile sistem arasındaki seçim, tamamen ne kadar risk almak istediğinizle ilgilidir. 18+ · Oyun bir eğlence biçimidir, kazanç garantisi değildir; lütfen sorumlu oynayın." },
    ],
    faq: [
      { q: "Sistem bahis her zaman daha mı avantajlı?", a: "Hayır. Riski dağıtır ama maliyeti yüksektir. Tüm seçimler tutarsa kombine aynı bütçeyle daha çok kazandırır." },
      { q: "Kombine kuponda kaç seçim ideal?", a: "Sabit bir sayı yoktur, ancak seçim sayısı arttıkça kazanma olasılığı hızla düşer. İki ile dört arası kuponlar dengeli kabul edilir." },
      { q: "Sistem bahsin maliyetini nasıl hesaplarım?", a: "Kombinasyon sayısını birim tutarla çarpın. Kupon ekranı toplam maliyeti oynamadan önce gösterir." },
      { q: "Kombinede bir maç iptal olursa ne olur?", a: "İptal edilen seçim genellikle geçersiz sayılır ve oranı bir olarak hesaplanır; kupon kalan seçimlerle değerlendirilir." },
      { q: "Sistem bahiste kısmi kazanç mümkün mü?", a: "Evet. Tutan kombinasyonlar kazanç üretir; kuponun tamamının tutması gerekmez." },
      { q: "Kombine oranları nasıl hesaplanır?", a: "Seçimlerin oranları birbiriyle çarpılır. Elde edilen toplam oran, bahis tutarıyla çarpılarak potansiyel kazanç bulunur." },
    ],
  },
  {
    slug: "hesap-dogrulama-kyc-neden-gerekli",
    title: "Hesap Doğrulama (KYC) Neden İsteniyor?",
    description:
      "KYC nedir, hangi belgeler istenir, doğrulama ne kadar sürer, belge neden reddedilir ve süreci ilk seferde tamamlamanın pratik yolları.",
    date: "2026-07-14",
    readingMinutes: 7,
    body: [
      { type: "p", text: "KYC, kullanıcının kim olduğunu doğrulayan standart bir kimlik denetimi sürecidir. Bankalardan kripto borsalarına kadar finansal işlem yapılan hemen her platformda uygulanır. Bahis sitelerinde de amacı aynıdır: yaş sınırını denetlemek, hesabın gerçek sahibini teyit etmek ve ödemelerin doğru kişiye ulaşmasını sağlamak." },
      { type: "h2", text: "Neden Zorunlu?" },
      { type: "p", text: "Doğrulama, hesabınızı sizden başkasının kullanmasını önleyen en güçlü korumadır. Aynı zamanda 18 yaş sınırının uygulanmasını sağlar ve para çekme talebinin hesap sahibine ödendiğini güvence altına alır. Bu yüzden doğrulama bir engel değil, hesabınızın koruma katmanıdır." },
      { type: "h2", text: "Hangi Belgeler İstenir?" },
      { type: "p", text: "Standart olarak üç grup belge istenir. Kimlik için nüfus cüzdanı, ehliyet veya pasaportun okunaklı bir görüntüsü; adres için son üç aya ait fatura veya banka ekstresi; ödeme yöntemi için ise kullandığınız kartın veya cüzdan hesabının size ait olduğunu gösteren bir belge." },
      { type: "h2", text: "Belge Neden Reddedilir?" },
      { type: "p", text: "Reddin en sık nedeni görüntü kalitesidir: bulanık fotoğraf, kesilmiş köşeler veya parlama nedeniyle okunamayan alanlar. İkinci sık neden, adres belgesinin tarihinin eski olmasıdır. Üçüncüsü ise belgedeki isim ile hesap adının farklı yazılmasıdır. Bu üç noktaya dikkat etmek çoğu reddi baştan önler." },
      { type: "h2", text: "Doğru Belge Nasıl Hazırlanır?" },
      { type: "p", text: "Belgeyi düz bir zemine koyun, doğrudan üstten ve gün ışığında fotoğraflayın. Dört köşesinin de kare içinde göründüğünden emin olun. Ekran görüntüsü yerine belgenin kendi fotoğrafını veya bankanızın ürettiği resmi PDF çıktısını kullanın. Dosya boyutu sınırını aşmamak için gereksiz yüksek çözünürlükten kaçının." },
      { type: "h2", text: "Süreç Ne Kadar Sürer?" },
      { type: "p", text: "Belgeler eksiksiz ve okunaklıysa inceleme genellikle kısa sürede tamamlanır. Yoğun dönemlerde veya ek belge gerektiğinde süre uzayabilir. Doğrulamayı ilk para çekme talebini beklemeden, üyelik açar açmaz tamamlamak en pratik yaklaşımdır; böylece çekim aşamasında hiç beklemezsiniz." },
      { type: "h2", text: "Belgelerin Güvenliği" },
      { type: "p", text: "Belgelerinizi yalnızca sitenin kendi hesap panelindeki yükleme alanından gönderin. Sohbet uygulaması, e-posta veya sosyal medya üzerinden kimlik belgesi paylaşmanız istenirse bu bir uyarı işaretidir. Resmi yükleme alanı dışındaki hiçbir kanala belge göndermeyin." },
      { type: "p", text: "Doğrulaması tamamlanmış bir hesap hem daha güvenlidir hem de ödeme süreçlerini sorunsuz kılar. 18+ · Oyun bir eğlence biçimidir, kazanç garantisi değildir; lütfen sorumlu oynayın." },
    ],
    faq: [
      { q: "KYC ne demek?", a: "Know Your Customer, yani müşterini tanı ilkesinin kısaltmasıdır. Kullanıcının kimliğinin belgeyle doğrulanması sürecini ifade eder." },
      { q: "Doğrulama yapmadan para çekebilir miyim?", a: "Genellikle hayır. İlk çekim talebinde kimlik doğrulaması istenir; bu adım tamamlanmadan ödeme yapılmaz." },
      { q: "Belgelerim ne kadar süre saklanır?", a: "Belgeler ilgili mevzuatın öngördüğü süre boyunca saklanır ve yalnızca doğrulama amacıyla kullanılır." },
      { q: "Adres belgem yoksa ne yapabilirim?", a: "Son üç aya ait banka ekstresi, elektrik, su, doğalgaz veya internet faturası kabul edilir. Adınız ve adresiniz görünür olmalıdır." },
      { q: "Doğrulama reddedildi, tekrar deneyebilir miyim?", a: "Evet. Ret gerekçesi bildirilir; belirtilen eksiği giderip belgeyi yeniden yükleyebilirsiniz." },
      { q: "Başkasının kartını hesabıma tanımlayabilir miyim?", a: "Hayır. Ödeme yöntemi hesap sahibinin kendi adına kayıtlı olmalıdır; aksi halde işlem reddedilir." },
    ],
  },
  {
    slug: "musteri-hizmetleri-nasil-kullanilir",
    title: "Müşteri Hizmetleri Nasıl Kullanılır? Sorununuzu Hızlı Çözün",
    description:
      "Canlı destek, e-posta ve sosyal kanalların farkı; hangi sorun için hangi kanalın uygun olduğu ve talebi ilk seferde çözdüren yazma yöntemi.",
    date: "2026-07-05",
    readingMinutes: 6,
    body: [
      { type: "p", text: "Müşteri hizmetleri, doğru kullanıldığında çoğu sorunu tek görüşmede çözer. Kullanıcıların yaşadığı gecikmelerin büyük bölümü, hatalı kanal seçiminden veya eksik bilgi paylaşımından kaynaklanır. Bu yazıda hangi durumda hangi kanalı seçeceğinizi ve talebinizi nasıl yazacağınızı anlatıyoruz." },
      { type: "h2", text: "Canlı Destek Ne Zaman Kullanılır?" },
      { type: "p", text: "Canlı destek, anlık ve kısa sorular için en hızlı kanaldır: giriş yapamama, kupon görüntüleme sorunu, bonus kodunun işlememesi gibi durumlar buraya uygundur. Görüşme genellikle birkaç dakika içinde başlar ve yazışma kaydı hesabınızda saklanır." },
      { type: "h2", text: "E-posta Ne Zaman Daha Uygun?" },
      { type: "p", text: "Belge göndermeniz gereken, detaylı açıklama isteyen veya birden fazla işlemi kapsayan konular e-posta için uygundur. Kimlik doğrulama, ödeme itirazı ve hesap kapatma talepleri bu gruba girer. E-posta yanıtı canlı destekten yavaştır, ancak yazılı ve izlenebilir bir kayıt bırakır." },
      { type: "h2", text: "Talebi Nasıl Yazmalısınız?" },
      { type: "p", text: "İyi bir destek mesajı üç şeyi içerir: ne olduğu, ne zaman olduğu ve ne beklediğiniz. Kullanıcı adınızı, işlem numarasını ve varsa hata mesajının ekran görüntüsünü ilk mesajda paylaşın. Bu bilgileri baştan vermek, karşılıklı soru cevap turlarını ortadan kaldırır ve çözümü belirgin biçimde hızlandırır." },
      { type: "h2", text: "Neyi Paylaşmamalısınız?" },
      { type: "p", text: "Şifrenizi hiçbir koşulda kimseyle paylaşmayın; destek ekibi şifrenizi asla istemez. Kart numaranızın tamamını, güvenlik kodunu veya SMS doğrulama kodunu da paylaşmayın. Bu bilgileri isteyen bir mesaj alırsanız, kanal resmi görünse bile işlemi durdurun ve durumu resmi destek üzerinden teyit edin." },
      { type: "h2", text: "Yanıt Gecikirse" },
      { type: "p", text: "Aynı konuda arka arkaya yeni talep açmak sırayı öne almaz, aksine kaydı bölerek süreci uzatır. Mevcut talebinize yanıt olarak yazın ve varsa talep numarasını belirtin. Yoğun saatlerde beklemek olağandır; acil olmayan konular için mesai saatleri içinde yazmak daha hızlı sonuç verir." },
      { type: "h2", text: "Görüşme Kaydını Saklayın" },
      { type: "p", text: "Ödeme, bonus veya hesap kısıtlaması gibi konularda yazışma kaydını saklamak faydalıdır. Konu ilerleyen günlerde tekrar gündeme gelirse, önceki görüşmeye atıf yapmak süreci hızlandırır." },
      { type: "p", text: "Doğru kanal ve net bir mesaj, çoğu sorunu tek seferde çözer. 18+ · Oyun bir eğlence biçimidir, kazanç garantisi değildir; lütfen sorumlu oynayın." },
    ],
    faq: [
      { q: "Canlı destek hangi saatlerde açık?", a: "Canlı destek genellikle 7/24 hizmet verir. Yoğun saatlerde bağlanma süresi bir miktar uzayabilir." },
      { q: "Destek ekibi şifremi ister mi?", a: "Hayır. Hiçbir koşulda şifreniz istenmez. Şifre isteyen bir mesaj aldıysanız paylaşmayın ve resmi kanaldan teyit edin." },
      { q: "Talebime ne kadar sürede dönüş yapılır?", a: "Canlı destekte yanıt genellikle dakikalar içindedir. E-posta talepleri konunun kapsamına göre daha uzun sürebilir." },
      { q: "Aynı konu için tekrar yazmalı mıyım?", a: "Hayır. Mevcut talebinize yanıt olarak yazın; yeni talep açmak kaydı böler ve süreci uzatır." },
      { q: "Şikayetimi nereye iletebilirim?", a: "Öncelikle resmi destek kanalına iletin ve talep numarasını saklayın. Çözülmezse yazışma kaydıyla üst kademeye taşınmasını isteyebilirsiniz." },
      { q: "Yazışma kaydına sonradan ulaşabilir miyim?", a: "Canlı destek görüşmeleri genellikle hesabınızda saklanır. E-posta yazışmaları ise kendi posta kutunuzda kalır." },
    ],
  },
  {
    slug: "handikap-bahsi-nedir",
    title: "Handikap Bahsi Nedir? Nasıl Oynanır?",
    description:
      "Handikap bahsi nedir, tek ve çift handikap farkı, Asya handikabı nasıl çalışır ve hangi maçlarda handikap tercih edilir.",
    date: "2026-06-26",
    readingMinutes: 7,
    body: [
      { type: "p", text: "Handikap bahsi, güçlü takıma sanal bir dezavantaj, zayıf takıma ise sanal bir avantaj vererek iki tarafın oranını birbirine yaklaştıran bahis türüdür. Favori takımın çok bariz olduğu ve maç sonucu oranının düşük kaldığı karşılaşmalarda tercih edilir." },
      { type: "h2", text: "Mantığı Nasıl İşler?" },
      { type: "p", text: "Diyelim ev sahibi çok güçlü ve galibiyet oranı 1.20 seviyesinde. Bu orana bahis yapmak çekici değildir. Handikap ile ev sahibine örneğin -1.5 gol yüklenir; kuponun tutması için ev sahibinin en az iki farkla kazanması gerekir. Karşılığında oran belirgin biçimde yükselir." },
      { type: "h2", text: "Artı ve Eksi Handikap" },
      { type: "p", text: "Eksi handikap favoriye verilir ve o takımın belirtilen farkı aşmasını şart koşar. Artı handikap ise zayıf tarafa verilir; o takım kaybetse bile belirtilen farkın altında kaldığında kupon tutar. Örneğin +1.5 handikaplı takım tek farkla yenilse de bahis kazanır." },
      { type: "h2", text: "Asya Handikabı" },
      { type: "p", text: "Asya handikabı beraberlik seçeneğini ortadan kaldırır ve bahsi iki sonuca indirger. Tam sayılı handikaplarda (0, -1, +1) skor tam olarak handikaba denk gelirse bahis iade edilir. Çeyrek değerlerde (-0.25, -0.75) bahis ikiye bölünür; yarısı bir seçeneğe, yarısı diğerine yazılır." },
      { type: "h2", text: "Hangi Maçlarda Mantıklı?" },
      { type: "p", text: "Güç farkının belirgin olduğu karşılaşmalarda handikap, düşük oranı yükselten pratik bir araçtır. Buna karşılık dengeli maçlarda handikap eklemek gereksiz risk üretir; orada maç sonucu ya da alt/üst daha sağlıklı okunur." },
      { type: "h2", text: "Sık Yapılan Hata" },
      { type: "p", text: "En yaygın hata, sırf oranı yükseltmek için gereğinden büyük handikap seçmektir. -2.5 handikap, favorinin üç farkla kazanmasını şart koşar; bu istatistiksel olarak çok daha nadir bir sonuçtur. Handikap seçerken takımın gerçek gol ortalamasına bakmak, oranın cazibesine bakmaktan daha güvenilirdir." },
      { type: "p", text: "Handikap, doğru maçta kullanıldığında değerli bir araçtır; her maça uygulanacak bir formül değildir. 18+ · Oyun bir eğlence biçimidir, kazanç garantisi değildir; lütfen sorumlu oynayın." },
    ],
    faq: [
      { q: "Handikap bahsi ile maç sonucu farkı nedir?", a: "Maç sonucu ham skora bakar. Handikapta ise takımlardan birine sanal gol eklenir veya çıkarılır; kupon bu düzeltilmiş skora göre değerlendirilir." },
      { q: "0 handikap ne demek?", a: "İki takım eşit kabul edilir. Maç berabere biterse bahis iade edilir; aksi halde kazanan takıma yapılan bahis kazanır." },
      { q: "Çeyrek handikap nasıl hesaplanır?", a: "Bahsiniz iki eşit parçaya bölünür. -0.75 handikapta yarısı -0.5, yarısı -1 olarak değerlendirilir; sonuca göre biri kazanıp diğeri iade olabilir." },
      { q: "Handikap bahsi hangi sporlarda var?", a: "Futbol, basketbol, tenis ve voleybol başta olmak üzere çoğu branşta sunulur. Basketbolda sayı, tenistedse set veya oyun üzerinden hesaplanır." },
      { q: "Handikapta uzatmalar sayılır mı?", a: "Kural olarak normal süre esas alınır. Uzatma ve penaltıların dahil olduğu özel bahis türleri ayrıca belirtilir." },
    ],
  },
  {
    slug: "alt-ust-bahsi-nedir",
    title: "Alt/Üst Bahsi Nedir? Nasıl Oynanır?",
    description:
      "Alt üst bahsi nedir, eşik değeri ne anlama gelir, 2.5 üst nasıl hesaplanır ve hangi maçlarda alt üst tercih edilir.",
    date: "2026-06-17",
    readingMinutes: 6,
    body: [
      { type: "p", text: "Alt/üst bahsi, karşılaşmadaki toplam gol, sayı veya korner gibi bir değerin belirlenen eşiğin altında mı üstünde mi kalacağına dair bahistir. Hangi takımın kazandığı sonucu etkilemez; yalnızca toplam değer dikkate alınır. Bu yönüyle maç sonucundan bağımsız bir bakış sunar." },
      { type: "h2", text: "Eşik Değeri Neden Buçuklu?" },
      { type: "p", text: "Eşikler genellikle 1.5, 2.5, 3.5 gibi buçuklu verilir. Bunun nedeni beraberlik ihtimalini ortadan kaldırmaktır: toplam gol asla 2.5 olamayacağı için sonuç ya alttadır ya üstte. Tam sayılı eşiklerde (2.0 gibi) skor eşiğe denk gelirse bahis iade edilir." },
      { type: "h2", text: "2.5 Üst Örneği" },
      { type: "p", text: "2.5 üst bahsi, maçta toplam üç veya daha fazla gol atılmasını gerektirir. 2-1, 3-0 ve 2-2 biten maçlar kazandırır; 1-1 ve 2-0 biten maçlar kaybettirir. Skorun kime ait olduğu önemli değildir, yalnızca toplam sayılır." },
      { type: "h2", text: "Hangi Verilere Bakılır?" },
      { type: "p", text: "Sağlıklı bir alt/üst kararı için iki takımın attığı ve yediği gol ortalaması, son karşılaşmalardaki toplam gol dağılımı ve oynanan lig ortalaması incelenir. Bazı ligler yapısal olarak daha gollüdür; bunu hesaba katmadan tek maç istatistiğine bakmak yanıltır." },
      { type: "h2", text: "Alt/Üst Sadece Gol Değildir" },
      { type: "p", text: "Korner sayısı, kart sayısı, taç atışı ve basketbolda toplam sayı için de alt/üst sunulur. Korner ve kart bahisleri hakem eğilimi ve takım oyun tarzıyla yakından ilişkilidir; bu iki değişken gol ortalamasından bağımsız değerlendirilmelidir." },
      { type: "h2", text: "Canlı Alt/Üst" },
      { type: "p", text: "Maç sürerken eşik ve oranlar yeniden hesaplanır. Erken gol gelen bir maçta üst oranı hızla düşer, alt oranı yükselir. Canlı alt/üst oynarken kalan süreyi ve oyunun temposunu birlikte değerlendirmek gerekir." },
      { type: "p", text: "Alt/üst, takım tarafı tutmadan oynanabildiği için birçok bahisçi tarafından daha okunabilir bulunur. 18+ · Oyun bir eğlence biçimidir, kazanç garantisi değildir; lütfen sorumlu oynayın." },
    ],
    faq: [
      { q: "Alt üst bahsinde uzatmalar sayılır mı?", a: "Kural olarak yalnızca normal süre sayılır. Uzatma dahil bahisler ayrı bir seçenek olarak sunulur." },
      { q: "2.5 alt ne demek?", a: "Maçta toplam iki veya daha az gol atılması gerekir. 0-0, 1-0 ve 1-1 sonuçları kazandırır." },
      { q: "Tam sayılı eşikte ne olur?", a: "Toplam skor eşiğe tam eşit olursa bahis genellikle iade edilir. Bu yüzden çoğu eşik buçuklu verilir." },
      { q: "Alt üst hangi istatistiğe bakarak seçilir?", a: "İki takımın gol ortalamaları, son maçlardaki toplam gol dağılımı ve lig ortalaması birlikte değerlendirilir." },
      { q: "Korner alt üst nasıl çalışır?", a: "Gol yerine toplam korner sayısı esas alınır. Mantık aynıdır; eşik üstünde veya altında kalması beklenir." },
    ],
  },
  {
    slug: "bahis-kuponu-nasil-yapilir",
    title: "Bahis Kuponu Nasıl Yapılır? Adım Adım",
    description:
      "Bahis kuponu nasıl hazırlanır: seçim ekleme, tutar belirleme, oran değişikliği onayı ve kuponu göndermeden önce kontrol edilecekler.",
    date: "2026-06-09",
    readingMinutes: 6,
    body: [
      { type: "p", text: "Bahis kuponu, seçtiğiniz bahisleri ve yatıracağınız tutarı bir arada tutan formdur. Kuponu doğru hazırlamak, oynadıktan sonra yaşanan çoğu şaşkınlığı baştan önler. Bu rehberde kupon oluşturmayı adım adım anlatıyoruz." },
      { type: "h2", text: "1. Karşılaşmayı ve Bahis Türünü Seç" },
      { type: "p", text: "Önce branşı, ardından karşılaşmayı açın. Karşılaşma sayfasında maç sonucu, alt/üst, handikap ve diğer türler listelenir. Seçtiğiniz orana tıkladığınızda bahis kupona eklenir. Bir maçta birbiriyle çakışan iki seçimi aynı kupona ekleyemezsiniz." },
      { type: "h2", text: "2. Kupon Türünü Belirle" },
      { type: "p", text: "Tek seçim yaptıysanız kupon tekli olur. Birden fazla seçim eklediğinizde kombine veya sistem seçebilirsiniz. Kombinede tüm seçimlerin tutması gerekir; sistemde seçimler alt kombinasyonlara bölünür ve bir kısmı tutmasa da kazanç mümkün olur." },
      { type: "h2", text: "3. Tutarı Gir" },
      { type: "p", text: "Bahis tutarını yazdığınızda ekranda potansiyel kazanç anında hesaplanır. Sistem kuponlarında girdiğiniz tutar kombinasyon sayısıyla çarpılır; toplam maliyeti göndermeden önce mutlaka kontrol edin. Alt ve üst bahis limitleri kupon ekranında görünür." },
      { type: "h2", text: "4. Oran Değişikliği Tercihini Ayarla" },
      { type: "p", text: "Kuponu gönderdiğiniz an ile onaylandığı an arasında oran değişebilir. Çoğu kupon ekranında bu durumda ne yapılacağını belirleyen bir seçenek bulunur: değişikliği otomatik kabul et, yalnızca yükselişleri kabul et veya her değişikliği onaya sun. Canlı bahiste bu ayar önemlidir." },
      { type: "h2", text: "5. Göndermeden Önce Son Kontrol" },
      { type: "p", text: "Seçimlerin doğru maça ait olduğunu, bahis türünü, tutarı ve toplam oranı bir kez daha okuyun. En sık yapılan hata, aynı isimli iki karşılaşmadan yanlış olanı seçmektir. Kupon onaylandıktan sonra seçim değiştirilemez." },
      { type: "h2", text: "Kupon Onaylandıktan Sonra" },
      { type: "p", text: "Onaylanan kupon hesap panelindeki bahis geçmişinde görünür. Buradan durumunu, potansiyel kazancı ve varsa erken kazanç teklifini takip edebilirsiniz. Maç sonuçlandığında kupon otomatik değerlendirilir." },
      { type: "p", text: "Kuponu acele göndermek yerine bir kez okumak, en ucuz hata önleme yöntemidir. 18+ · Oyun bir eğlence biçimidir, kazanç garantisi değildir; lütfen sorumlu oynayın." },
    ],
    faq: [
      { q: "Kuponu gönderdikten sonra iptal edebilir miyim?", a: "Onaylanmış kupon kural olarak iptal edilemez. Bazı karşılaşmalarda erken kazanç seçeneği sunulur, bu iptal değil güncel değerden kapatmadır." },
      { q: "Aynı maçtan iki seçim ekleyebilir miyim?", a: "Birbiriyle çakışmayan seçimler bazı durumlarda birleştirilebilir. Çakışan seçimler kupona eklenmez." },
      { q: "Potansiyel kazanç nasıl hesaplanır?", a: "Kombine kuponda seçim oranları çarpılır, çıkan toplam oran bahis tutarıyla çarpılır." },
      { q: "Kupon neden reddedildi?", a: "En sık nedeni onay süresi içinde oranın değişmesidir. Limit aşımı ve maçın başlaması da ret nedeni olabilir." },
      { q: "Kupon geçmişimi nereden görürüm?", a: "Hesap panelindeki bahis geçmişi bölümünden tarih bazlı tüm kuponlarınıza ulaşabilirsiniz." },
    ],
    steps: [
      { name: "Kar\u015f\u0131la\u015fma ve bahis t\u00fcr\u00fcn\u00fc se\u00e7", text: "Bran\u015f\u0131 ve kar\u015f\u0131la\u015fmay\u0131 a\u00e7\u0131n, ard\u0131ndan oynamak istedi\u011finiz orana t\u0131klayarak se\u00e7imi kupona ekleyin." },
      { name: "Kupon t\u00fcr\u00fcn\u00fc belirle", text: "Tek se\u00e7im yapt\u0131ysan\u0131z kupon tekli olur. Birden fazla se\u00e7imde kombine veya sistem aras\u0131nda tercih yap\u0131n." },
      { name: "Tutar\u0131 gir", text: "Bahis tutar\u0131n\u0131 yaz\u0131n ve ekranda hesaplanan potansiyel kazanc\u0131 kontrol edin. Sistem kuponlar\u0131nda toplam maliyeti mutlaka do\u011frulay\u0131n." },
      { name: "Oran de\u011fi\u015fikli\u011fi tercihini ayarla", text: "Kupon onaylanana kadar oran de\u011fi\u015febilir. Otomatik kabul, yaln\u0131zca y\u00fckseli\u015f veya her de\u011fi\u015fikli\u011fi onaya sunma se\u00e7eneklerinden birini belirleyin." },
      { name: "Son kontrol\u00fc yap ve g\u00f6nder", text: "Se\u00e7imlerin do\u011fru ma\u00e7a ait oldu\u011funu, bahis t\u00fcr\u00fcn\u00fc, tutar\u0131 ve toplam oran\u0131 bir kez daha okuyun; ard\u0131ndan kuponu onaylay\u0131n." },
    ],
  },
  {
    slug: "para-cekme-talebi-neden-bekliyor",
    title: "Para Çekme Talebi Neden Bekliyor? 7 Yaygın Neden",
    description:
      "Çekim talebi neden beklemede kalır: eksik doğrulama, açık bonus, yöntem uyuşmazlığı, limit aşımı ve banka saatleri.",
    date: "2026-05-30",
    readingMinutes: 6,
    body: [
      { type: "p", text: "Çekim talebinizin beklemede görünmesi çoğu zaman bir sorun değil, sürecin normal bir aşamasıdır. Yine de beklemenin uzaması genellikle belirli ve çözülebilir nedenlerden kaynaklanır. En sık karşılaşılan yedi nedeni sırayla ele alıyoruz." },
      { type: "h2", text: "1. Kimlik Doğrulaması Tamamlanmamış" },
      { type: "p", text: "En yaygın neden budur. İlk çekimde kimlik, adres ve ödeme yöntemi doğrulaması istenir. Belgeler yüklenmemişse talep otomatik olarak bekletilir. Çözümü basittir: hesap panelindeki doğrulama bölümünden belgeleri yükleyin. Bunu üyelik açar açmaz yapmak beklemeyi tamamen ortadan kaldırır." },
      { type: "h2", text: "2. Açık Bonus ve Çevrim Şartı" },
      { type: "p", text: "Hesabınızda çevrimi tamamlanmamış bir bonus varsa çekim talebi işleme alınmayabilir. Bonus bakiyesi ile ana bakiye ayrı değerlendirilir. Hesap panelinden bonusun çevrim durumunu kontrol edin; şart tamamlanmadıysa ya çevrimi bitirmeniz ya da bonusu iptal etmeniz gerekir." },
      { type: "h2", text: "3. Yöntem Uyuşmazlığı" },
      { type: "p", text: "Çekim, kural olarak yatırım yaptığınız yöntemle yapılır. Farklı bir yöntem seçtiyseniz talep incelemeye alınır veya reddedilir. Ayrıca ödeme yönteminin hesap sahibiyle aynı kişiye ait olması zorunludur; başkasının kartı veya hesabı kabul edilmez." },
      { type: "h2", text: "4. Limit Aşımı" },
      { type: "p", text: "Her yöntemin günlük, haftalık ve işlem başına limitleri vardır. Üst limiti aşan tutarlar otomatik olarak birden fazla işleme bölünebilir; bu da toplam süreyi uzatır. Alt limitin altındaki talepler ise hiç işleme alınmaz." },
      { type: "h2", text: "5. Yüksek Tutar İncelemesi" },
      { type: "p", text: "Belirli bir eşiğin üzerindeki çekimlerde ek doğrulama yapılması standart bir uygulamadır. Bu bir şüphe göstergesi değil, rutin bir kontroldür. Ek belge istenirse hesap bildirimlerinizde görünür." },
      { type: "h2", text: "6. Banka ve Ağ Saatleri" },
      { type: "p", text: "Site tarafında onaylanan bir işlem, ödeme sağlayıcısının çalışma saatlerine takılabilir. Banka havalesi hafta sonu ve resmi tatillerde ilk iş gününe sarkar. Kripto transferlerinde ise ağ yoğunluğu doğrulama süresini uzatabilir." },
      { type: "h2", text: "7. Aynı Talebi Tekrar Oluşturmak" },
      { type: "p", text: "Bekleyen bir talep varken yenisini açmak süreci hızlandırmaz; aksine kuyruğu karmaşıklaştırır ve inceleme süresini uzatır. Mevcut talebin sonucunu bekleyin, gerekirse destek ekibine talep numarasıyla yazın." },
      { type: "p", text: "Doğrulaması tamam, bonusu kapalı ve kendi yöntemiyle yapılan çekimler beklenen sürede sonuçlanır. 18+ · Oyun bir eğlence biçimidir, kazanç garantisi değildir; lütfen sorumlu oynayın." },
    ],
    faq: [
      { q: "Bekleyen talebi iptal edebilir miyim?", a: "Talep henüz onaylanmadıysa çoğu durumda iptal edilebilir. Sağlayıcıya iletildikten sonra iptal mümkün değildir." },
      { q: "Ne kadar beklemek normal?", a: "Yönteme göre değişir. Elektronik cüzdanlar en hızlısıdır; banka havalesi iş günü, kripto ise ağ yoğunluğuna bağlıdır." },
      { q: "Bonusu iptal edersem çekim açılır mı?", a: "Genellikle evet. Bonus iptal edildiğinde bonus bakiyesi ve kazancı silinir, ana bakiyeniz çekilebilir hale gelir." },
      { q: "Ek belge istendi, ne yapmalıyım?", a: "Hesap panelindeki yükleme alanından belgeyi gönderin. Sohbet veya sosyal medya üzerinden belge paylaşmayın." },
      { q: "Destek ekibine ne yazmalıyım?", a: "Talep numarası, tarih, tutar ve seçtiğiniz yöntemi ilk mesajda verin. Bu bilgiler karşılıklı soru turlarını ortadan kaldırır." },
    ],
  },
  {
    slug: "hesap-kapatma-nasil-yapilir",
    title: "Hesap Kapatma Nasıl Yapılır? Kalıcı Kapatma ve Mola",
    description:
      "Hesap kapatma adımları, geçici dondurma ile kalıcı kapatma farkı, bakiye ne olur ve kendini dışlama araçları.",
    date: "2026-05-21",
    readingMinutes: 5,
    body: [
      { type: "p", text: "Hesabınızı kapatmak istediğinizde önünüzde birden fazla seçenek vardır. Kalıcı kapatma tek yol değildir; geçici dondurma ve kendini dışlama araçları çoğu durumda daha uygun bir çözümdür. Hangisinin size uyduğunu bilmek önemlidir." },
      { type: "h2", text: "Geçici Dondurma" },
      { type: "p", text: "Belirli bir süre ara vermek istiyorsanız hesabınızı dondurabilirsiniz. Bu süre boyunca giriş yapamaz, bahis oynayamaz ve promosyon bildirimi almazsınız. Süre dolduğunda hesap kendiliğinden yeniden açılır. Bakiyeniz ve geçmişiniz korunur." },
      { type: "h2", text: "Kendini Dışlama" },
      { type: "p", text: "Kendini dışlama, dondurmadan daha güçlü bir araçtır. Genellikle daha uzun süreler için tanımlanır ve süre dolmadan geri alınamaz. Oyun alışkanlığınızın kontrolden çıktığını düşünüyorsanız en etkili koruma budur." },
      { type: "h2", text: "Kalıcı Kapatma" },
      { type: "p", text: "Kalıcı kapatma talebi müşteri hizmetlerine iletilir. Talep işleme alınmadan önce hesabınızda bekleyen işlem olmadığı ve bakiyenizin çekildiği kontrol edilir. Kapatılan hesabın yeniden açılması genellikle mümkün değildir; bu yüzden karar öncesi dondurmayı değerlendirin." },
      { type: "h2", text: "Bakiye Ne Olur?" },
      { type: "p", text: "Kapatma öncesinde bakiyenizi çekmeniz gerekir. Kimlik doğrulamanız tamamlanmamışsa önce onu tamamlayın, çünkü doğrulanmamış hesaptan ödeme yapılmaz. Bekleyen bir çekim talebi varsa sonuçlanmasını bekleyin." },
      { type: "h2", text: "Nasıl Talep Edilir?" },
      { type: "p", text: "En sağlıklı yol e-posta ile yazılı talep göndermektir; böylece kayıt kalır. Mesajda kullanıcı adınızı, talebin türünü (dondurma, dışlama veya kalıcı kapatma) ve varsa süreyi belirtin. Canlı destek üzerinden de başlatılabilir ancak yazılı kayıt bırakmak daha güvenlidir." },
      { type: "p", text: "Ara vermek de bir karardır ve her zaman kalıcı olması gerekmez. 18+ · Oyun bir eğlence biçimidir, kazanç garantisi değildir; lütfen sorumlu oynayın." },
    ],
    faq: [
      { q: "Kapattığım hesabı geri açabilir miyim?", a: "Kalıcı kapatma genellikle geri alınamaz. Geri dönüş ihtimalini korumak istiyorsanız dondurma seçeneğini tercih edin." },
      { q: "Dondurma süresi ne kadar olabilir?", a: "Genellikle birkaç günden birkaç aya kadar seçenekler sunulur. Süre dolduğunda hesap otomatik açılır." },
      { q: "Bakiyem kapatınca ne olur?", a: "Kapatma öncesi bakiyenizi çekmeniz gerekir. Doğrulama tamamlanmadan ödeme yapılmaz." },
      { q: "Kendini dışlama ile dondurma farkı nedir?", a: "Dondurma süre dolunca kendiliğinden biter. Kendini dışlama daha uzun sürelidir ve süresi dolmadan geri alınamaz." },
      { q: "Kapatma talebi ne kadar sürer?", a: "Bekleyen işlem yoksa genellikle kısa sürede tamamlanır. Açık çekim talebi varsa önce o sonuçlanır." },
    ],
  },
  {
    slug: "sifremi-unuttum-nasil-sifirlarim",
    title: "Şifremi Unuttum — Nasıl Sıfırlarım?",
    description:
      "Şifre sıfırlama adımları, sıfırlama e-postası gelmiyorsa ne yapılır ve yeni şifreyi güvenli belirleme kuralları.",
    date: "2026-05-12",
    readingMinutes: 5,
    body: [
      { type: "p", text: "Şifre unutmak sık karşılaşılan ve hızlı çözülen bir durumdur. Sıfırlama süreci birkaç dakika sürer; asıl önemli olan yeni şifreyi doğru belirlemek ve sıfırlama sırasında dolandırıcılık girişimlerine karşı dikkatli olmaktır." },
      { type: "h2", text: "Sıfırlama Adımları" },
      { type: "p", text: "Giriş ekranındaki şifremi unuttum bağlantısına tıklayın. Kayıtlı e-posta adresinizi veya kullanıcı adınızı girin. Sistem, hesabınıza tanımlı e-posta adresine tek kullanımlık bir sıfırlama bağlantısı gönderir. Bağlantıya tıklayıp yeni şifrenizi belirlediğinizde işlem tamamlanır." },
      { type: "h2", text: "E-posta Gelmiyorsa" },
      { type: "p", text: "Önce spam ve tanıtımlar klasörünü kontrol edin. Kayıt sırasında kullandığınız adresi doğru yazdığınızdan emin olun; farklı bir adres girildiyse bağlantı oraya gitmez. Birkaç dakika bekleyip yeniden gönderim isteyin. Sorun sürerse müşteri hizmetlerine kullanıcı adınızla yazın." },
      { type: "h2", text: "Bağlantının Süresi Dolmuş" },
      { type: "p", text: "Sıfırlama bağlantıları güvenlik gereği kısa süre geçerlidir ve tek kullanımlıktır. Süresi dolmuş bir bağlantı çalışmaz; bu bir hata değil, koruma mekanizmasıdır. Yeni bağlantı talep edip hemen kullanın." },
      { type: "h2", text: "Yeni Şifreyi Belirlerken" },
      { type: "p", text: "Başka hiçbir sitede kullanmadığınız, en az on iki karakterlik bir şifre seçin. Büyük harf, küçük harf, rakam ve sembol karıştırın. Doğum tarihi, isim ve ardışık rakam gibi tahmin edilebilir kalıplardan kaçının. Şifre yöneticisi kullanıyorsanız oradan üretmek en pratik yoldur." },
      { type: "h2", text: "Dikkat: Sıfırlama Dolandırıcılığı" },
      { type: "p", text: "Sıfırlama kodunu veya bağlantısını hiç kimseyle paylaşmayın. Destek ekibi asla şifrenizi veya doğrulama kodunuzu istemez. Sizden kod isteyen bir mesaj alırsanız, kanal resmi görünse bile işlemi durdurun ve durumu resmi destek üzerinden teyit edin." },
      { type: "p", text: "Şifre sıfırlama basit bir işlemdir; asıl kazanç, yeni şifreyi bir daha unutmayacağınız şekilde güvenli saklamaktır. 18+ · Oyun bir eğlence biçimidir, kazanç garantisi değildir; lütfen sorumlu oynayın." },
    ],
    faq: [
      { q: "Sıfırlama e-postası ne kadar sürede gelir?", a: "Genellikle birkaç dakika içinde. Gelmiyorsa spam klasörünü kontrol edin ve yeniden gönderim isteyin." },
      { q: "Kayıtlı e-postama erişemiyorum, ne yapmalıyım?", a: "Müşteri hizmetlerine yazın. Kimlik doğrulaması sonrası e-posta adresi güncellenebilir." },
      { q: "Sıfırlama bağlantısı çalışmıyor.", a: "Bağlantılar tek kullanımlık ve kısa sürelidir. Yeni bağlantı talep edip hemen kullanın." },
      { q: "Şifremi kim isteyebilir?", a: "Hiç kimse. Destek ekibi dahil hiçbir yetkili şifrenizi veya doğrulama kodunuzu istemez." },
      { q: "Şifre değişince oturumlarım kapanır mı?", a: "Çoğu sistemde açık oturumlar güvenlik gereği sonlandırılır ve yeniden giriş yapmanız istenir." },
    ],
    steps: [
      { name: "S\u0131f\u0131rlama ba\u011flant\u0131s\u0131n\u0131 iste", text: "Giri\u015f ekran\u0131ndaki \u015fifremi unuttum ba\u011flant\u0131s\u0131na t\u0131klay\u0131n ve kay\u0131tl\u0131 e-posta adresinizi veya kullan\u0131c\u0131 ad\u0131n\u0131z\u0131 girin." },
      { name: "E-postay\u0131 kontrol et", text: "Hesab\u0131n\u0131za tan\u0131ml\u0131 adrese gelen tek kullan\u0131ml\u0131k s\u0131f\u0131rlama ba\u011flant\u0131s\u0131n\u0131 a\u00e7\u0131n. Gelmezse spam ve tan\u0131t\u0131mlar klas\u00f6r\u00fcne bak\u0131n." },
      { name: "Yeni \u015fifreyi belirle", text: "Ba\u015fka hi\u00e7bir sitede kullanmad\u0131\u011f\u0131n\u0131z, en az on iki karakterlik bir \u015fifre girin. Tahmin edilebilir kal\u0131plardan ka\u00e7\u0131n\u0131n." },
      { name: "Oturumlar\u0131 yenile", text: "\u015eifre de\u011fi\u015fince a\u00e7\u0131k oturumlar g\u00fcvenlik gere\u011fi sonland\u0131r\u0131l\u0131r; yeni \u015fifrenizle tekrar giri\u015f yap\u0131n." },
    ],
  },
  ];
